/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    2: typeof import('./components/InfiniteScroll copy 2.vue')['default']
    3: typeof import('./components/InfiniteScroll copy 3.vue')['default']
    4: typeof import('./components/InfiniteScroll copy 4.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    copy: typeof import('./components/InfiniteScroll copy.vue')['default']
    HelloWorld: typeof import("./src/components/HelloWorld.vue")["default"]
    infiniteScroll: typeof import("./components/infiniteScroll.vue")["default"]
    InfiniteScroll: typeof import('./components/InfiniteScroll.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
